### ISSUE TITLE
Needs packaging

### ISSUE THREAD

**Issue by rilian-la-te** [rilian-la-te/xfce4-sntray-plugin#22]
@sunweaver do you want to package this?

**Comment by sunweaver** [comment]
Hmmm... I thought Unit193 would be working on that... I probably hand that over...

**Comment by sunweaver** [comment]
Pinged him on IRC (#debian-ayatana on irc.debian.org)... He is from the Xubuntu team.

**Comment by sunweaver** [comment]
OT here: (me also has vala-panel-extras 95% ready, but needs to finalize debian/copyright with all the copyright holders of those nasty country flags... very painful!!!)

**Comment by sunweaver** [comment]
Similar project... Have you compared your approach from theirs?
https://git.xfce.org/panel-plugins/xfce4-statusnotifier-plugin/

**Comment by rilian-la-te** [comment]
Pros of me:
1. My project supports XFCE, MATE, ValaPanel and budgie (as appmenu). For ValaPanel soon it will be only one tray (so, absolutely needed).
2. I support some private DBusMenu properties from vala-panel-extras.
3. I support Ayatana Labels
4. Very flexible multiline layout.
5. Have QRichTextParser (better Qt tooltip handling)

Pros of they, AFAIK:
1. Have more powerful position handling
2. Can remember items
3. Can activate menu on right-click (Me only on left)

**Comment by sunweaver** [comment]
@rilian-la-te: I have uploaded this project to Debian now. However, the mate-sntray-plugin fails to load in MATE 1.20 (Debian unstable). How can I provide debug information?

**Comment by sunweaver** [comment]
Or rather, could you install a Debian testing system yourself, install the corresponding packages from Debian unstable and find out what's wrong? That would speed up the process of getting things to work properly in Debian. If you could do that, big THANKS from here!!!

Mike

**Comment by rilian-la-te** [comment]
Can you provide a debug info? I think this is CMake problem. Can you provide a packaging log? Maybe I can fix it without Debian installed.

**Comment by sunweaver** [comment]
Here you go...

On Saturday, March 3, 2018, Konstantin wrote:
> Can you provide a debug info? I think this is CMake problem. Can you provide a packaging log? Maybe I can fix it without Debian installed. 

https://buildd.debian.org/status/package.php?p=xfce4-sntray-plugin

-- 
Sent from my Fairphone 2 (running Sailfish OS)

**Comment by rilian-la-te** [comment]
I need an install log and files in a package.

**Comment by rilian-la-te** [comment]
Because debian used non-standard layout.

**Comment by sunweaver** [comment]
On  Sa 03 Mär 2018 19:59:42 CET, Konstantin wrote:

> I need an install log and files in a package.

```
[mike@minobo gosa (master)]$ dpkg -L mate-sntray-plugin
/.
/usr
/usr/lib
/usr/lib/mate-panel
/usr/lib/mate-panel/sntray-mate
/usr/share
/usr/share/dbus-1
/usr/share/dbus-1/services
/usr/share/dbus-1/services/org.mate.panel.applet.SNTrayAppletFactory.service
/usr/share/doc
/usr/share/doc/mate-sntray-plugin
/usr/share/doc/mate-sntray-plugin/changelog.Debian.gz
/usr/share/doc/mate-sntray-plugin/copyright
/usr/share/mate-panel
/usr/share/mate-panel/applets
/usr/share/mate-panel/applets/org.vala-panel.SNTray.mate-panel-applet
```

```
[mike@minobo gosa (master)]$ dpkg -L xfce4-sntray-plugin
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/xfce4
/usr/lib/x86_64-linux-gnu/xfce4/panel
/usr/lib/x86_64-linux-gnu/xfce4/panel/plugins
/usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libsntray-xfce.so
/usr/share
/usr/share/doc
/usr/share/doc/xfce4-sntray-plugin
/usr/share/doc/xfce4-sntray-plugin/changelog.Debian.gz
/usr/share/doc/xfce4-sntray-plugin/copyright
/usr/share/xfce4
/usr/share/xfce4/panel
/usr/share/xfce4/panel/plugins
/usr/share/xfce4/panel/plugins/sntray.desktop
```

```
[mike@minobo gosa (master)]$ dpkg -L budgie-sntray-plugin
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/budgie-desktop
/usr/lib/x86_64-linux-gnu/budgie-desktop/plugins
/usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/libsntray-budgie.so
/usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/sntray-budgie.plugin
/usr/share
/usr/share/doc
/usr/share/doc/budgie-sntray-plugin
/usr/share/doc/budgie-sntray-plugin/changelog.Debian.gz
/usr/share/doc/budgie-sntray-plugin/copyright
[mike@minobo gosa (master)]$
```

```
[mike@minobo xfce4-sntray-plugin (master)]$ dpkg -L vala-sntray-plugin
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/vala-panel
/usr/lib/x86_64-linux-gnu/vala-panel/applets
/usr/lib/x86_64-linux-gnu/vala-panel/applets/libsntray-valapanel.so
/usr/lib/x86_64-linux-gnu/vala-panel/applets/sntray.plugin
/usr/share
/usr/share/doc
/usr/share/doc/vala-sntray-plugin
/usr/share/doc/vala-sntray-plugin/changelog.Debian.gz
/usr/share/doc/vala-sntray-plugin/copyright
/usr/share/glib-2.0
/usr/share/glib-2.0/schemas
/usr/share/glib-2.0/schemas/org.valapanel.toplevel.sntray.gschema.xml
```

```
[mike@minobo gosa (master)]$ dpkg -L xfce4-sntray-plugin-common
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/xfce4-sntray-plugin-common
/usr/share/doc/xfce4-sntray-plugin-common/README.md
/usr/share/doc/xfce4-sntray-plugin-common/changelog.Debian.gz
/usr/share/doc/xfce4-sntray-plugin-common/copyright
/usr/share/locale
/usr/share/locale/aa
/usr/share/locale/aa/LC_MESSAGES
/usr/share/locale/aa/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ab
/usr/share/locale/ab/LC_MESSAGES
/usr/share/locale/ab/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ae
/usr/share/locale/ae/LC_MESSAGES
/usr/share/locale/ae/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/af
/usr/share/locale/af/LC_MESSAGES
/usr/share/locale/af/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ak
/usr/share/locale/ak/LC_MESSAGES
/usr/share/locale/ak/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/am
/usr/share/locale/am/LC_MESSAGES
/usr/share/locale/am/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/an
/usr/share/locale/an/LC_MESSAGES
/usr/share/locale/an/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ar
/usr/share/locale/ar/LC_MESSAGES
/usr/share/locale/ar/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/as
/usr/share/locale/as/LC_MESSAGES
/usr/share/locale/as/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ast
/usr/share/locale/ast/LC_MESSAGES
/usr/share/locale/ast/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/av
/usr/share/locale/av/LC_MESSAGES
/usr/share/locale/av/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ay
/usr/share/locale/ay/LC_MESSAGES
/usr/share/locale/ay/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/az
/usr/share/locale/az/LC_MESSAGES
/usr/share/locale/az/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ba
/usr/share/locale/ba/LC_MESSAGES
/usr/share/locale/ba/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/be
/usr/share/locale/be/LC_MESSAGES
/usr/share/locale/be/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/bg
/usr/share/locale/bg/LC_MESSAGES
/usr/share/locale/bg/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/bh
/usr/share/locale/bh/LC_MESSAGES
/usr/share/locale/bh/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/bi
/usr/share/locale/bi/LC_MESSAGES
/usr/share/locale/bi/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/bm
/usr/share/locale/bm/LC_MESSAGES
/usr/share/locale/bm/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/bn
/usr/share/locale/bn/LC_MESSAGES
/usr/share/locale/bn/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/bo
/usr/share/locale/bo/LC_MESSAGES
/usr/share/locale/bo/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/br
/usr/share/locale/br/LC_MESSAGES
/usr/share/locale/br/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/bs
/usr/share/locale/bs/LC_MESSAGES
/usr/share/locale/bs/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ca
/usr/share/locale/ca/LC_MESSAGES
/usr/share/locale/ca/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ce
/usr/share/locale/ce/LC_MESSAGES
/usr/share/locale/ce/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ch
/usr/share/locale/ch/LC_MESSAGES
/usr/share/locale/ch/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ckb
/usr/share/locale/ckb/LC_MESSAGES
/usr/share/locale/ckb/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/co
/usr/share/locale/co/LC_MESSAGES
/usr/share/locale/co/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/cr
/usr/share/locale/cr/LC_MESSAGES
/usr/share/locale/cr/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/cs
/usr/share/locale/cs/LC_MESSAGES
/usr/share/locale/cs/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/cu
/usr/share/locale/cu/LC_MESSAGES
/usr/share/locale/cu/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/cv
/usr/share/locale/cv/LC_MESSAGES
/usr/share/locale/cv/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/cy
/usr/share/locale/cy/LC_MESSAGES
/usr/share/locale/cy/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/da
/usr/share/locale/da/LC_MESSAGES
/usr/share/locale/da/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/de
/usr/share/locale/de/LC_MESSAGES
/usr/share/locale/de/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/dv
/usr/share/locale/dv/LC_MESSAGES
/usr/share/locale/dv/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/dz
/usr/share/locale/dz/LC_MESSAGES
/usr/share/locale/dz/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ee
/usr/share/locale/ee/LC_MESSAGES
/usr/share/locale/ee/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/el
/usr/share/locale/el/LC_MESSAGES
/usr/share/locale/el/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/en_AU
/usr/share/locale/en_AU/LC_MESSAGES
/usr/share/locale/en_AU/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/en_CA
/usr/share/locale/en_CA/LC_MESSAGES
/usr/share/locale/en_CA/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/en_GB
/usr/share/locale/en_GB/LC_MESSAGES
/usr/share/locale/en_GB/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/eo
/usr/share/locale/eo/LC_MESSAGES
/usr/share/locale/eo/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/es
/usr/share/locale/es/LC_MESSAGES
/usr/share/locale/es/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/et
/usr/share/locale/et/LC_MESSAGES
/usr/share/locale/et/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/eu
/usr/share/locale/eu/LC_MESSAGES
/usr/share/locale/eu/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/fa
/usr/share/locale/fa/LC_MESSAGES
/usr/share/locale/fa/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ff
/usr/share/locale/ff/LC_MESSAGES
/usr/share/locale/ff/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/fi
/usr/share/locale/fi/LC_MESSAGES
/usr/share/locale/fi/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/fj
/usr/share/locale/fj/LC_MESSAGES
/usr/share/locale/fj/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/fo
/usr/share/locale/fo/LC_MESSAGES
/usr/share/locale/fo/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/fr
/usr/share/locale/fr/LC_MESSAGES
/usr/share/locale/fr/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/fr_CA
/usr/share/locale/fr_CA/LC_MESSAGES
/usr/share/locale/fr_CA/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/fy
/usr/share/locale/fy/LC_MESSAGES
/usr/share/locale/fy/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ga
/usr/share/locale/ga/LC_MESSAGES
/usr/share/locale/ga/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/gd
/usr/share/locale/gd/LC_MESSAGES
/usr/share/locale/gd/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/gl
/usr/share/locale/gl/LC_MESSAGES
/usr/share/locale/gl/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/gn
/usr/share/locale/gn/LC_MESSAGES
/usr/share/locale/gn/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/gu
/usr/share/locale/gu/LC_MESSAGES
/usr/share/locale/gu/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/gv
/usr/share/locale/gv/LC_MESSAGES
/usr/share/locale/gv/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ha
/usr/share/locale/ha/LC_MESSAGES
/usr/share/locale/ha/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/he
/usr/share/locale/he/LC_MESSAGES
/usr/share/locale/he/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/hi
/usr/share/locale/hi/LC_MESSAGES
/usr/share/locale/hi/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ho
/usr/share/locale/ho/LC_MESSAGES
/usr/share/locale/ho/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/hr
/usr/share/locale/hr/LC_MESSAGES
/usr/share/locale/hr/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ht
/usr/share/locale/ht/LC_MESSAGES
/usr/share/locale/ht/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/hu
/usr/share/locale/hu/LC_MESSAGES
/usr/share/locale/hu/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/hy
/usr/share/locale/hy/LC_MESSAGES
/usr/share/locale/hy/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/hz
/usr/share/locale/hz/LC_MESSAGES
/usr/share/locale/hz/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ia
/usr/share/locale/ia/LC_MESSAGES
/usr/share/locale/ia/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/id
/usr/share/locale/id/LC_MESSAGES
/usr/share/locale/id/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ie
/usr/share/locale/ie/LC_MESSAGES
/usr/share/locale/ie/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ig
/usr/share/locale/ig/LC_MESSAGES
/usr/share/locale/ig/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ii
/usr/share/locale/ii/LC_MESSAGES
/usr/share/locale/ii/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ik
/usr/share/locale/ik/LC_MESSAGES
/usr/share/locale/ik/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/io
/usr/share/locale/io/LC_MESSAGES
/usr/share/locale/io/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/is
/usr/share/locale/is/LC_MESSAGES
/usr/share/locale/is/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/it
/usr/share/locale/it/LC_MESSAGES
/usr/share/locale/it/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/iu
/usr/share/locale/iu/LC_MESSAGES
/usr/share/locale/iu/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ja
/usr/share/locale/ja/LC_MESSAGES
/usr/share/locale/ja/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/jv
/usr/share/locale/jv/LC_MESSAGES
/usr/share/locale/jv/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ka
/usr/share/locale/ka/LC_MESSAGES
/usr/share/locale/ka/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/kg
/usr/share/locale/kg/LC_MESSAGES
/usr/share/locale/kg/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ki
/usr/share/locale/ki/LC_MESSAGES
/usr/share/locale/ki/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/kj
/usr/share/locale/kj/LC_MESSAGES
/usr/share/locale/kj/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/kk
/usr/share/locale/kk/LC_MESSAGES
/usr/share/locale/kk/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/kl
/usr/share/locale/kl/LC_MESSAGES
/usr/share/locale/kl/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/km
/usr/share/locale/km/LC_MESSAGES
/usr/share/locale/km/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/kn
/usr/share/locale/kn/LC_MESSAGES
/usr/share/locale/kn/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ko
/usr/share/locale/ko/LC_MESSAGES
/usr/share/locale/ko/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/kr
/usr/share/locale/kr/LC_MESSAGES
/usr/share/locale/kr/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ks
/usr/share/locale/ks/LC_MESSAGES
/usr/share/locale/ks/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ku
/usr/share/locale/ku/LC_MESSAGES
/usr/share/locale/ku/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/kv
/usr/share/locale/kv/LC_MESSAGES
/usr/share/locale/kv/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/kw
/usr/share/locale/kw/LC_MESSAGES
/usr/share/locale/kw/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ky
/usr/share/locale/ky/LC_MESSAGES
/usr/share/locale/ky/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/la
/usr/share/locale/la/LC_MESSAGES
/usr/share/locale/la/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/lb
/usr/share/locale/lb/LC_MESSAGES
/usr/share/locale/lb/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/lg
/usr/share/locale/lg/LC_MESSAGES
/usr/share/locale/lg/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/li
/usr/share/locale/li/LC_MESSAGES
/usr/share/locale/li/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ln
/usr/share/locale/ln/LC_MESSAGES
/usr/share/locale/ln/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/lo
/usr/share/locale/lo/LC_MESSAGES
/usr/share/locale/lo/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/lt
/usr/share/locale/lt/LC_MESSAGES
/usr/share/locale/lt/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/lu
/usr/share/locale/lu/LC_MESSAGES
/usr/share/locale/lu/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/lv
/usr/share/locale/lv/LC_MESSAGES
/usr/share/locale/lv/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/mg
/usr/share/locale/mg/LC_MESSAGES
/usr/share/locale/mg/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/mh
/usr/share/locale/mh/LC_MESSAGES
/usr/share/locale/mh/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/mi
/usr/share/locale/mi/LC_MESSAGES
/usr/share/locale/mi/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/mk
/usr/share/locale/mk/LC_MESSAGES
/usr/share/locale/mk/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ml
/usr/share/locale/ml/LC_MESSAGES
/usr/share/locale/ml/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/mn
/usr/share/locale/mn/LC_MESSAGES
/usr/share/locale/mn/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/mo
/usr/share/locale/mo/LC_MESSAGES
/usr/share/locale/mo/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/mr
/usr/share/locale/mr/LC_MESSAGES
/usr/share/locale/mr/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ms
/usr/share/locale/ms/LC_MESSAGES
/usr/share/locale/ms/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/mt
/usr/share/locale/mt/LC_MESSAGES
/usr/share/locale/mt/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/my
/usr/share/locale/my/LC_MESSAGES
/usr/share/locale/my/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/na
/usr/share/locale/na/LC_MESSAGES
/usr/share/locale/na/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/nb
/usr/share/locale/nb/LC_MESSAGES
/usr/share/locale/nb/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/nd
/usr/share/locale/nd/LC_MESSAGES
/usr/share/locale/nd/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ne
/usr/share/locale/ne/LC_MESSAGES
/usr/share/locale/ne/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ng
/usr/share/locale/ng/LC_MESSAGES
/usr/share/locale/ng/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/nl
/usr/share/locale/nl/LC_MESSAGES
/usr/share/locale/nl/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/nn
/usr/share/locale/nn/LC_MESSAGES
/usr/share/locale/nn/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/no
/usr/share/locale/no/LC_MESSAGES
/usr/share/locale/no/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/nr
/usr/share/locale/nr/LC_MESSAGES
/usr/share/locale/nr/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/nv
/usr/share/locale/nv/LC_MESSAGES
/usr/share/locale/nv/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ny
/usr/share/locale/ny/LC_MESSAGES
/usr/share/locale/ny/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/oc
/usr/share/locale/oc/LC_MESSAGES
/usr/share/locale/oc/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/oj
/usr/share/locale/oj/LC_MESSAGES
/usr/share/locale/oj/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/om
/usr/share/locale/om/LC_MESSAGES
/usr/share/locale/om/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/or
/usr/share/locale/or/LC_MESSAGES
/usr/share/locale/or/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/os
/usr/share/locale/os/LC_MESSAGES
/usr/share/locale/os/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/pa
/usr/share/locale/pa/LC_MESSAGES
/usr/share/locale/pa/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/pi
/usr/share/locale/pi/LC_MESSAGES
/usr/share/locale/pi/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/pl
/usr/share/locale/pl/LC_MESSAGES
/usr/share/locale/pl/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ps
/usr/share/locale/ps/LC_MESSAGES
/usr/share/locale/ps/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/pt
/usr/share/locale/pt/LC_MESSAGES
/usr/share/locale/pt/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/pt_BR
/usr/share/locale/pt_BR/LC_MESSAGES
/usr/share/locale/pt_BR/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/qu
/usr/share/locale/qu/LC_MESSAGES
/usr/share/locale/qu/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/rm
/usr/share/locale/rm/LC_MESSAGES
/usr/share/locale/rm/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/rn
/usr/share/locale/rn/LC_MESSAGES
/usr/share/locale/rn/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ro
/usr/share/locale/ro/LC_MESSAGES
/usr/share/locale/ro/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ru
/usr/share/locale/ru/LC_MESSAGES
/usr/share/locale/ru/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/rue
/usr/share/locale/rue/LC_MESSAGES
/usr/share/locale/rue/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/rw
/usr/share/locale/rw/LC_MESSAGES
/usr/share/locale/rw/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/sa
/usr/share/locale/sa/LC_MESSAGES
/usr/share/locale/sa/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/sc
/usr/share/locale/sc/LC_MESSAGES
/usr/share/locale/sc/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/sd
/usr/share/locale/sd/LC_MESSAGES
/usr/share/locale/sd/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/se
/usr/share/locale/se/LC_MESSAGES
/usr/share/locale/se/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/sg
/usr/share/locale/sg/LC_MESSAGES
/usr/share/locale/sg/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/si
/usr/share/locale/si/LC_MESSAGES
/usr/share/locale/si/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/sk
/usr/share/locale/sk/LC_MESSAGES
/usr/share/locale/sk/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/sl
/usr/share/locale/sl/LC_MESSAGES
/usr/share/locale/sl/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/sm
/usr/share/locale/sm/LC_MESSAGES
/usr/share/locale/sm/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/sma
/usr/share/locale/sma/LC_MESSAGES
/usr/share/locale/sma/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/sn
/usr/share/locale/sn/LC_MESSAGES
/usr/share/locale/sn/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/so
/usr/share/locale/so/LC_MESSAGES
/usr/share/locale/so/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/sq
/usr/share/locale/sq/LC_MESSAGES
/usr/share/locale/sq/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/sr
/usr/share/locale/sr/LC_MESSAGES
/usr/share/locale/sr/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ss
/usr/share/locale/ss/LC_MESSAGES
/usr/share/locale/ss/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/st
/usr/share/locale/st/LC_MESSAGES
/usr/share/locale/st/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/su
/usr/share/locale/su/LC_MESSAGES
/usr/share/locale/su/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/sv
/usr/share/locale/sv/LC_MESSAGES
/usr/share/locale/sv/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/sw
/usr/share/locale/sw/LC_MESSAGES
/usr/share/locale/sw/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ta
/usr/share/locale/ta/LC_MESSAGES
/usr/share/locale/ta/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/te
/usr/share/locale/te/LC_MESSAGES
/usr/share/locale/te/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/tg
/usr/share/locale/tg/LC_MESSAGES
/usr/share/locale/tg/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/th
/usr/share/locale/th/LC_MESSAGES
/usr/share/locale/th/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ti
/usr/share/locale/ti/LC_MESSAGES
/usr/share/locale/ti/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/tk
/usr/share/locale/tk/LC_MESSAGES
/usr/share/locale/tk/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/tl
/usr/share/locale/tl/LC_MESSAGES
/usr/share/locale/tl/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/tn
/usr/share/locale/tn/LC_MESSAGES
/usr/share/locale/tn/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/to
/usr/share/locale/to/LC_MESSAGES
/usr/share/locale/to/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/tr
/usr/share/locale/tr/LC_MESSAGES
/usr/share/locale/tr/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ts
/usr/share/locale/ts/LC_MESSAGES
/usr/share/locale/ts/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/tt
/usr/share/locale/tt/LC_MESSAGES
/usr/share/locale/tt/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/tw
/usr/share/locale/tw/LC_MESSAGES
/usr/share/locale/tw/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ty
/usr/share/locale/ty/LC_MESSAGES
/usr/share/locale/ty/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ug
/usr/share/locale/ug/LC_MESSAGES
/usr/share/locale/ug/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/uk
/usr/share/locale/uk/LC_MESSAGES
/usr/share/locale/uk/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ur
/usr/share/locale/ur/LC_MESSAGES
/usr/share/locale/ur/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/uz
/usr/share/locale/uz/LC_MESSAGES
/usr/share/locale/uz/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/ve
/usr/share/locale/ve/LC_MESSAGES
/usr/share/locale/ve/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/vi
/usr/share/locale/vi/LC_MESSAGES
/usr/share/locale/vi/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/vo
/usr/share/locale/vo/LC_MESSAGES
/usr/share/locale/vo/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/wa
/usr/share/locale/wa/LC_MESSAGES
/usr/share/locale/wa/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/wo
/usr/share/locale/wo/LC_MESSAGES
/usr/share/locale/wo/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/xh
/usr/share/locale/xh/LC_MESSAGES
/usr/share/locale/xh/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/yi
/usr/share/locale/yi/LC_MESSAGES
/usr/share/locale/yi/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/yo
/usr/share/locale/yo/LC_MESSAGES
/usr/share/locale/yo/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/za
/usr/share/locale/za/LC_MESSAGES
/usr/share/locale/za/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/zh
/usr/share/locale/zh/LC_MESSAGES
/usr/share/locale/zh/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/zh_CN
/usr/share/locale/zh_CN/LC_MESSAGES
/usr/share/locale/zh_CN/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/zh_HK
/usr/share/locale/zh_HK/LC_MESSAGES
/usr/share/locale/zh_HK/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/zh_TW
/usr/share/locale/zh_TW/LC_MESSAGES
/usr/share/locale/zh_TW/LC_MESSAGES/xfce4-sntray-plugin.mo
/usr/share/locale/zu
/usr/share/locale/zu/LC_MESSAGES
/usr/share/locale/zu/LC_MESSAGES/xfce4-sntray-plugin.mo
```
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by rilian-la-te** [comment]
All others, except MATE, works?

**Comment by sunweaver** [comment]
Hi

On Sunday, March 4, 2018, Konstantin wrote:
> All others, except MATE, works? 

Nope, xfce plugin seems to fail, too. Haven't tested budgie and vala-panel, yet.

Mike

-- 
Sent from my Fairphone 2 (running Sailfish OS)

**Comment by rilian-la-te** [comment]
Fail or cannot load? If cannot load, I need a layout. If fail, I need a Debian.

**Comment by rilian-la-te** [comment]
Try now. I changes paths logic as in appmenu (appmenu works on Debian afaik)

**Comment by rilian-la-te** [comment]
Did you tried latest revision?

**Comment by sunweaver** [comment]
The patches look promising. Testing is difficult as 4.8 and master HEAD are 17 commits apart. Cherry-picking all seems quite like a hassle. Do you think it's possible to tag a new release?

**Comment by rilian-la-te** [comment]
You do not need to cherry-pick all) sniproxy is turned off))) but if you want, I can tag a new release.

**Comment by sunweaver** [comment]
On  Mi 07 Mär 2018 15:38:05 CET, Konstantin wrote:

> You do not need to cherry-pick all) sniproxy is turned off))) but if  
> you want, I can tag a new release.

please do. Thanks!

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by rilian-la-te** [comment]
Done, try tarball. SNIProxy is removed)

**Comment by sunweaver** [comment]
On  Mi 07 Mär 2018 18:58:37 CET, Konstantin wrote:

> Done, try tarball. SNIProxy is removed)

The 0.4.9 version fails to build from source:

```
[...]
  [ 95%] Linking C shared library libsntray-valapanel.so
cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src && /usr/bin/cmake -E  
cmake_link_script CMakeFiles/sntray-valapanel.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=.  
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time  
-D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -Wl,-O1  
-Wl,-z,defs -shared -Wl,-soname,libsntray-valapanel.so -o  
libsntray-valapanel.so  
CMakeFiles/sntray-valapanel.dir/vala-panel-sntray-applet.c.o  
CMakeFiles/sntray-valapanel.dir/sntray.gresource.c.o -lvalapanel  
-lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject  
-lcairo -lgdk_pixbuf-2.0 -lpeas-1.0 -lgmodule-2.0 -lgio-2.0  
-lgirepository-1.0 -lgobject-2.0 -lglib-2.0 libsntray-core.a  
/usr/lib/x86_64-linux-gnu/libgio-2.0.so  
/usr/lib/x86_64-linux-gnu/libgio-2.0.so  
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so  
/usr/lib/x86_64-linux-gnu/libglib-2.0.so  
/usr/lib/x86_64-linux-gnu/libgtk-3.so  
/usr/lib/x86_64-linux-gnu/libgdk-3.so -lm
libsntray-core.a(snitem.c.o): In function `status_notifier_item_change_icon':
./obj-x86_64-linux-gnu/src/./src/snitem.vala:367: undefined reference  
to `cairo_format_stride_for_width'
./obj-x86_64-linux-gnu/src/./src/snitem.vala:367: undefined reference  
to `gdk_pixbuf_new_from_data'
./obj-x86_64-linux-gnu/src/./src/snitem.vala:377: undefined reference  
to `gdk_pixbuf_get_width'
./obj-x86_64-linux-gnu/src/./src/snitem.vala:377: undefined reference  
to `gdk_pixbuf_get_width'
./obj-x86_64-linux-gnu/src/./src/snitem.vala:378: undefined reference  
to `gdk_pixbuf_scale_simple'
libsntray-core.a(snitem.c.o): In function  
`status_notifier_item_iface_new_icon_cb':
./obj-x86_64-linux-gnu/src/./src/snitem.vala:436: undefined reference  
to `gdk_pixbuf_get_width'
./obj-x86_64-linux-gnu/src/./src/snitem.vala:436: undefined reference  
to `gdk_pixbuf_get_height'
./obj-x86_64-linux-gnu/src/./src/snitem.vala:441: undefined reference  
to `gdk_pixbuf_scale_simple'
libsntray-core.a(snitem.c.o): In function  
`status_notifier_item_unbox_tooltip':
./obj-x86_64-linux-gnu/src/./src/snitem.vala:310: undefined reference  
to `pango_parse_markup'
collect2: error: ld returned 1 exit status
make[3]: *** [src/CMakeFiles/sntray-valapanel.dir/build.make:145:  
src/libsntray-valapanel.so] Error 1
make[3]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
make[2]: *** [CMakeFiles/Makefile2:518:  
src/CMakeFiles/sntray-valapanel.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
make[3]: Entering directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
[ 97%] Linking C shared library libsntray-xfce.so
cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src && /usr/bin/cmake -E  
cmake_link_script CMakeFiles/sntray-xfce.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=.  
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time  
-D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -Wl,-O1  
-Wl,-z,defs -shared -Wl,-soname,libsntray-xfce.so -o libsntray-xfce.so  
CMakeFiles/sntray-xfce.dir/xfce4-sntray-applet.c.o  
CMakeFiles/sntray-xfce.dir/sntray.gresource.c.o -lxfce4panel-2.0  
-lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject  
-lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgmodule-2.0 -lxfce4util  
-lxfconf-0 -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lglib-2.0  
libsntray-core.a /usr/lib/x86_64-linux-gnu/libgio-2.0.so  
/usr/lib/x86_64-linux-gnu/libgio-2.0.so  
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so  
/usr/lib/x86_64-linux-gnu/libglib-2.0.so  
/usr/lib/x86_64-linux-gnu/libgtk-3.so  
/usr/lib/x86_64-linux-gnu/libgdk-3.so -lm
libsntray-core.a(snitem.c.o): In function `status_notifier_item_change_icon':
./obj-x86_64-linux-gnu/src/./src/snitem.vala:367: undefined reference  
to `cairo_format_stride_for_width'
./obj-x86_64-linux-gnu/src/./src/snitem.vala:367: undefined reference  
to `gdk_pixbuf_new_from_data'
./obj-x86_64-linux-gnu/src/./src/snitem.vala:377: undefined reference  
to `gdk_pixbuf_get_width'
./obj-x86_64-linux-gnu/src/./src/snitem.vala:377: undefined reference  
to `gdk_pixbuf_get_width'
./obj-x86_64-linux-gnu/src/./src/snitem.vala:378: undefined reference  
to `gdk_pixbuf_scale_simple'
libsntray-core.a(snitem.c.o): In function  
`status_notifier_item_iface_new_icon_cb':
./obj-x86_64-linux-gnu/src/./src/snitem.vala:436: undefined reference  
to `gdk_pixbuf_get_width'
./obj-x86_64-linux-gnu/src/./src/snitem.vala:436: undefined reference  
to `gdk_pixbuf_get_height'
./obj-x86_64-linux-gnu/src/./src/snitem.vala:441: undefined reference  
to `gdk_pixbuf_scale_simple'
libsntray-core.a(snitem.c.o): In function  
`status_notifier_item_unbox_tooltip':
./obj-x86_64-linux-gnu/src/./src/snitem.vala:310: undefined reference  
to `pango_parse_markup'
collect2: error: ld returned 1 exit status
make[3]: *** [src/CMakeFiles/sntray-xfce.dir/build.make:147:  
src/libsntray-xfce.so] Error 1
make[3]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
make[2]: *** [CMakeFiles/Makefile2:316:  
src/CMakeFiles/sntray-xfce.dir/all] Error 2
make[3]: Entering directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
[100%] Linking C shared library libsntray-budgie.so
cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src && /usr/bin/cmake -E  
cmake_link_script CMakeFiles/sntray-budgie.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=.  
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time  
-D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -Wl,-O1  
-Wl,-z,defs -shared -Wl,-soname,libsntray-budgie.so -o  
libsntray-budgie.so  
CMakeFiles/sntray-budgie.dir/sntray-applet-budgie.c.o  
CMakeFiles/sntray-budgie.dir/sntray.gresource.c.o -lbudgie-plugin  
-lpeas-1.0 -lgmodule-2.0 -lgirepository-1.0 -lgio-2.0 -lgtk-3 -lgdk-3  
-lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo  
-lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 libsntray-core.a  
-lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject  
-lcairo -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0  
/usr/lib/x86_64-linux-gnu/libgio-2.0.so  
/usr/lib/x86_64-linux-gnu/libgio-2.0.so  
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so  
/usr/lib/x86_64-linux-gnu/libglib-2.0.so  
/usr/lib/x86_64-linux-gnu/libgtk-3.so  
/usr/lib/x86_64-linux-gnu/libgdk-3.so -lm
make[3]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
make[2]: Entering directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
[100%] Built target sntray-budgie
make[2]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
make[1]: *** [Makefile:155: all] Error 2
dh_auto_build: cd obj-x86_64-linux-gnu && make -j4 -O returned exit code 2
make: *** [debian/rules:9: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
--------------------------------------------------------------------------------
Build finished at 2018-03-11T11:34:29Z
```

Can you please check? Thanks!

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by rilian-la-te** [comment]
Will look for it, but on Arch it builds. I definitely need a configured Debian...

**Comment by rilian-la-te** [comment]
AFAIK, this is fixed by 0fdc67e49170fbfe0d9b0383f97c7b87ad48d5d9

**Comment by sunweaver** [comment]
Nope, this doesn't fix it.

In fact the 0.4.9 tarball contains 0fdc67e. Which is peculiar, because it is not part of the 0.4.9 Git tag.

Do you create the tarballs, that you provide, manually? If so, they should exactly match with what you tag in Git.

**Comment by sunweaver** [comment]
It's on my side... I did not have libglib2.0-dev under Build-Depends.

**Comment by sunweaver** [comment]
Nope, still same FTBFS. Any other build dependency that I miss?

https://anonscm.debian.org/cgit/pkg-ayatana/xfce4-sntray-plugin.git/tree/debian/control#n9

**Comment by rilian-la-te** [comment]
Yes, I create tarballs manually, because git clone cannot create a
buildable tarball. About build dependencies - I need to check it with
actual Debian, because build dep lioks fine for me. Maybe some Debian
Linking rules forbide a linking...

**Comment by sunweaver** [comment]
On  So 11 Mär 2018 14:36:17 CET, Konstantin wrote:

> Yes, I create tarballs manually, because git clone cannot create a
> buildable tarball. About build dependencies - I need to check it with
> actual Debian, because build dep lioks fine for me. Maybe some Debian
> Linking rules forbide a linking...

Make sure you have Debian testing/unstable for your build tests.

Thanks,
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by rilian-la-te** [comment]
It will not work on stable anyway.

**Comment by rilian-la-te** [comment]
@sunweaver I have some comments about your override in vala-panel-appmenu.
1. You should not set override to ```blacklist=['anjuta','appmenu-mate','glade','mate-hud','mate-indicator-applet','mate-indicator-applet-appmenu','mate-indicator-applet-complete','mate-menu','mate-panel']```, because ```mate-panel``` and ```mate-hud``` and ```mate-menu``` should be hardcoded (I will check).
2. I will release a new vala-panel-appmenu tag soon.


About xfce4-sntray-plugin: I cannot get FTBFS on latest testing (no unstable required).
 But I was building an applet, not a Debian package. How I should build a debian package from this source?

**Comment by rilian-la-te** [comment]
Sorry, I do not know how to build debian package from git(

**Comment by rilian-la-te** [comment]
It is strange. It works with applet, but not with debuild. What options debian enforces to packages?

**Comment by sunweaver** [comment]
On  Mo 12 Mär 2018 22:43:59 CET, Konstantin wrote:

> It is strange. It works with applet, but not with debuild. What  
> options debian enforces to packages?

Options in what way? Compiler options? I can take another look on  
Wednesday, if then still needed...

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by rilian-la-te** [comment]
With latest master it builds package and works (at least MATE and vala-panel)

**Comment by sunweaver** [comment]
This seems to work now. Can you please provide a release tag, so we get this into Debian unstable and get some more feedback from other testers?

I observed issues when mate-indicator-applet + ayatana-indicator-application were installed and configured in the session. I wonder, if I should add a conflict between those packages.

The MATE desktop will move towards Ayatana Indicators support for Debian buster and Ubuntu 20.04. Then no sntray is needed there. We should make sure that we catch corner cases, I guess.

Also MATE's stock Notification Area applet has received SNI support recently. In Debian, the a11y people request enabling it.

So, it might be useful to have some checking code in mate-sntray (and the XFCE sntray, too), to see if the SNI DBus socket is already in use or not.

**Comment by sunweaver** [comment]
Let me know, if I shall file the above as a new issue.

**Comment by rilian-la-te** [comment]
And it has checking code and use existing dbus socket, if it is found.

**Comment by rilian-la-te** [comment]
It should work with outer Registrar, I have a mate-panel and use both
sntray and notification area. About ayatana - it also should work. If it is
not, file a bug, please.

**Comment by rilian-la-te** [comment]
> Also MATE's stock Notification Area applet has received SNI support recently. In Debian, the a11y people request enabling it.

I know, but stock SNI has a way less features.

> So, it might be useful to have some checking code in mate-sntray (and the XFCE sntray, too), to see if the SNI DBus socket is already in use or not.

I already have it [here](https://github.com/rilian-la-te/xfce4-sntray-plugin/blob/master/src/snhost.vala).

> 
The MATE desktop will move towards Ayatana Indicators support for Debian buster and Ubuntu 20.04. Then no sntray is needed there. We should make sure that we catch corner cases, I guess.

No need for sntray removal for MATE. See screenshot:
![screenshot at 2018-03-17 10-02-26](https://user-images.githubusercontent.com/1329638/37552646-8d102172-29ca-11e8-9bdd-179333b93e2b.png)

This is a MATE panel with both SNTray and stock SNI. As you see, weather extra on stock SNI is not using Ayatana label, but on SNTray is.

**Comment by rilian-la-te** [comment]
Tag is done.

**Comment by sunweaver** [comment]
I must admit, I can't tell from the screen shot, what is what. Can you explain? Also, what exactly do you understand as Ayatana labels?

Thanks and sorry this is taking so long on my side to put the jigsaw together ..

Mike

On Saturday, March 17, 2018, Konstantin wrote:
> Also MATE's stock Notification Area applet has received SNI support recently. In Debian, the a11y people request enabling it.
> I know, but stock SNI has a way less features.
> So, it might be useful to have some checking code in mate-sntray (and the XFCE sntray, too), to see if the SNI DBus socket is already in use or not.
> I already have it here.
> The MATE desktop will move towards Ayatana Indicators support for Debian buster and Ubuntu 20.04. Then no sntray is needed there. We should make sure that we catch corner cases, I guess.
> No need for sntray removal for MATE. See screenshot:
> ￼
> This is a MATE panel with both SNTray and stock SNI. As you see, weather extra on stock SNI is not using Ayatana label, but on SNTray is. 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.￼
>

-- 
Sent from my Fairphone 2 (running Sailfish OS)

**Comment by rilian-la-te** [comment]
1. At left you can see SNTray. It contains nm-applet and vala-panel-extras-weather.
2. At center is MATE default notification area. You can also see nm-applet and vala-panel-extras-weather (only sun icon, no temperature). Temperature on left is showing by Ayatana labels.
3. At right is default MATE clock with weather,

**Comment by rilian-la-te** [comment]
Ayatana labels is about showing text in system tray.
